config:
  mqtt_broker_id: openhab
devices:
  # Tasmota item
  - type: TASMOTA_SONOFF_MINI
    channels:
      POWER:
        id: room_tasmota_singlechannel
        name: Tasmota item (single-channel)
        expire: 1h
        groups:
          - g_light_all
          - g_light_kg

  - name: Aldi test
    id: aldi_test
    zigbee_id: '0x60a423fffe4b91cf'
    type: ALDI_FILAMENT
    icon: light
    expire: 1m
    groups:
      sw:
      - g_light_all
      - g_light_kg
      - g_light_kg_hobbyraum
      ct:
      - g_light_astro_color

  - name: Room temp (sleeping)
    id: sz_climate
    zigbee_id: '0xa4c1383cc92cbbd2'
    type: TUYA_TEMPERATURE_SENSOR_TS0201

  - name: KU Light SW
    id: ku_light_switch
    zigbee_id: '0x842e14fffe1267fb'
    type: TUYA_WALL_SWITCH_TS0601
    channels:
      l1:
        id: ku_light_switch_haupt
        name: KU Light Haupt (Wall SW)
        groups:
          sw:
          - g_light_all
          - g_light_eg
          - g_light_eg_ku
      l2:
        id: ku_light_switch_arbeit
        name: KU Light Arbeit (Wall SW)
        expire: 3h
        groups:
          sw:
          - g_light_all
          - g_light_eg
          - g_light_eg_ku

  - name: SZ CO2
    id: sz_co2
    type: PETROWS_CO2_SENSOR
    device_id: 5C:CF:7F:68:19:46
